name: Java CI with Maven

on:
  pull_request:
    branches:
      - "main"
      - "dependabot/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17, 21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Clear Maven Cache
        uses: ./.github/actions/clear-maven-cache/action.yml
      - name: Setup JDK
        uses: ./.github/actions/setup-jdk/action.yml
        with:
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: mvn clean compile package
        shell: bash

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.actor != 'dependabot[bot]'
    strategy:
      matrix:
        java-version: [17, 21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: ./.github/actions/setup-jdk/action.yml
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run Tests with Maven
        run: mvn test
        shell: bash

  lint:
    runs-on: ubuntu-latest
    needs: build
    if: github.actor != 'dependabot[bot]'
    strategy:
      matrix:
        java-version: [17, 21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: ./.github/actions/setup-jdk/action.yml
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run Lint with Maven
        run: mvn checkstyle:check
        shell: bash
