name: Java CI with Maven

on:
  pull_request:
    branches:
      - "main"
      - "dependabot/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17, 21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Clear Maven Cache
        uses: ./.github/actions/clear-maven-cache
      - name: Setup JDK
        uses: ./.github/actions/setup-jdk
        with:
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: mvn clean compile package
        shell: bash

  test:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        java-version: [17, 21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: ./.github/actions/setup-jdk
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run Tests with Maven
        run: mvn test
        shell: bash

  lint:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        java-version: [17, 21]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: ./.github/actions/setup-jdk
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run Lint with Maven
        run: mvn checkstyle:check
        shell: bash

  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor == 'dependabot[bot]' }}
    steps:
      - name: Auto approve Dependabot PR
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    runs-on: ubuntu-latest
    needs: auto-approve
    if: ${{ github.triggering_actor == 'dependabot[bot]' }}
    steps:
      - name: Merge Dependabot PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.issue.number;
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
            });
            if (pr.data.state === 'open') {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr_number,
              });
            }
