name: Java CI with Maven

on:
  pull_request:
    branches:
      - "main"
      - "dependabot/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17, 21]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Clear Maven Cache
        run: rm -rf ~/.m2/repository/org/openjfx
        shell: bash

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Verify Java Version
        run: java -version
        shell: bash

      - name: Build with Maven
        run: mvn clean compile package
        shell: bash

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.actor != 'dependabot[bot]'  # Exclude Dependabot from this job
    strategy:
      matrix:
        java-version: [17, 21]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Run Tests with Maven
        run: mvn test
        shell: bash

  lint:
    runs-on: ubuntu-latest
    needs: build
    if: github.actor != 'dependabot[bot]'  # Exclude Dependabot from this job
    strategy:
      matrix:
        java-version: [17, 21]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Run Lint with Maven
        run: mvn checkstyle:check
        shell: bash
