name: Reusable Java CI Workflow

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Clear Maven Cache
        uses: ./.github/actions/clear-maven-cache

      - name: Set up JDK
        uses: ./.github/actions/setup-jdk
        with:
          java-version: ${{ inputs.java-version }}

      - name: Build with Maven
        run: mvn clean compile package
        shell: bash

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: ./.github/actions/setup-jdk
        with:
          java-version: ${{ inputs.java-version }}

      - name: Run Tests with Maven
        run: mvn test
        shell: bash

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: ./.github/actions/setup-jdk
        with:
          java-version: ${{ inputs.java-version }}

      - name: Run Lint with Maven
        run: mvn checkstyle:check
        shell: bash
